name: Node.js + Docker Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Download repository code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Packages
        run: npm install

      # Run tests
      - name: Run Tests
        run: echo "No tests yet"

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t myapp .

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Download repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Packages
        run: npm install

      # Dummy publish step
      - name: Publish Package
        run: echo "Package publish skipped"
